version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: charan678/cyclopes-cicd:latest

    steps:
      - checkout
      - run:
          name: install dependencies
          command: python3 setup.py install
  test:
    docker:
      - image: charan678/cyclopes-cicd:latest
    steps:
      - checkout
      - run:
          name: Install tests dependencies and run the tests
          command: python3 setup.py test