version: 2

jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: python3 setup.py install
  test:
    steps:
      - checkout
      - run:
          name: Install tests dependencies and run the tests
          command: python3 setup.py test